### ISSUE TITLE
Unhandled error: Unexpected end of ZLIB input stream

### ISSUE THREAD

**Issue by Luke1887** [cherweg/logstash-input-s3-sns-sqs#6]
Sometimes logstash seems to hang, process is running but journalctl -u logstash.service says: 

Mär 22 10:17:53 ip-someip.eu-central-1.compute.internal logstash[12870]: Exception in thread "Ruby-0-Thread-2483: /usr/share/logstash/vendor/bundle/jruby/2.3.0/gems/logstash-input-s3-sns-sqs-1.4.2/lib/logstash/inputs/s3snssqs.rb:408" java.io.EOFException: Unexpected end of ZLIB input stream

There is no other hint in /var/log/logstash/* and it's quite hard to monitor this.
I think a simple rescue and error-message in log will be great.

**Comment by stijnvanrenterghem** [comment]
I have the same problem. What is the cause of this error?

**Comment by christianherweg0807** [comment]
Could you please add an exception @stijnvanrenterghem ?
This issue is quite old and everything is refactored...
In the actual implementation this is a buffered GzipInputStream:
https://github.com/cherweg/logstash-input-s3-sns-sqs/blob/480cf2f5a8fab0d8d217ed04f4647c867865095a/lib/logstash/inputs/s3snssqs/log_processor.rb#L91
